<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductCatalogSeeder extends Seeder
{
    /**
     * Alimente un échantillon public et représentatif du catalogue vélo 2W de Michelin.
     *
     * Le catalogue propriétaire complet (~442 produits) n'est PAS versionné dans ce
     * dépôt public. Cet échantillon sélectionné utilise de vraies valeurs du catalogue et
     * couvre les quatre segments de cyclistes ainsi que le scénario de démo : Marc roule sur un
     * Power Gravel usé (ETRTO 40-622) et se voit proposer en montée de gamme le Power Gravel RS (42-622),
     * tous deux sur des roues 622. `expected_life_km` et `rolling_resistance_watts`
     * sont des estimations métier (absentes du catalogue source) et ne sont renseignés
     * que pour la paire gravel de la démo.
     */
    public function run(): void
    {
        foreach ($this->products() as $product) {
            Product::updateOrCreate(
                ['ean_code' => $product['ean_code']],
                $product,
            );
        }
    }

    /**
     * Échantillon de catalogue sélectionné. La clé d'upsert est `ean_code` (unique par taille) ;
     * `global_id` est l'identifiant de *gamme* du catalogue, partagé entre les tailles d'une même gamme.
     *
     * @return list<array<string, mixed>>
     */
    private function products(): array
    {
        return [
            // ── GRAVEL ─────────────────────────────────────────────────────
            [
                'global_id' => 'BI-38',
                'web_range_name' => 'Power Gravel',
                'segment' => 'GRAVEL',
                'width_etrto' => 40,
                'diameter_etrto' => 622,
                'tpi' => 120,
                'min_pressure_bar' => 3.0,
                'max_pressure_bar' => 4.5,
                'rubber_tech' => 'MAGI-X',
                'casing_tech' => 'BEAD TO BEAD SHIELD',
                'reinforcement_tech' => null,
                'ebike_tech' => 'E-BIKE READY',
                'terrain_types' => ['ASPHALT', 'OFFROAD HARD PACKED', 'OFFROAD MIXED'],
                'use' => 'VERSATILE,TREKKING,E-GRAVEL,E-TREKKING',
                'expected_life_km' => 4000,
                'rolling_resistance_watts' => 22.0,
                'weight_g' => 490,
                'ean_code' => '3528702637890',
                'price_eur' => null,
                'image_url' => null,
            ],
            [
                'global_id' => 'BI-177',
                'web_range_name' => 'Power Gravel RS',
                'segment' => 'GRAVEL',
                'width_etrto' => 42,
                'diameter_etrto' => 622,
                'tpi' => 120,
                'min_pressure_bar' => null,
                'max_pressure_bar' => 4.5,
                'rubber_tech' => 'GUM-X',
                'casing_tech' => 'BEAD TO BEAD SHIELD',
                'reinforcement_tech' => null,
                'ebike_tech' => null,
                'terrain_types' => ['ASPHALT', 'OFFROAD HARD PACKED'],
                'use' => 'RACING,E-GRAVEL',
                'expected_life_km' => 3000,
                'rolling_resistance_watts' => 16.0,
                'weight_g' => 445,
                'ean_code' => '3528705648480',
                'price_eur' => null,
                'image_url' => null,
            ],
            [
                'global_id' => 'BI-129',
                'web_range_name' => 'Power Adventure',
                'segment' => 'GRAVEL',
                'width_etrto' => 48,
                'diameter_etrto' => 584,
                'tpi' => 100,
                'min_pressure_bar' => 2.5,
                'max_pressure_bar' => 4.0,
                'rubber_tech' => 'GUM-X',
                'casing_tech' => 'BEAD TO BEAD SHIELD',
                'reinforcement_tech' => null,
                'ebike_tech' => 'E-BIKE READY',
                'terrain_types' => ['ASPHALT', 'OFFROAD HARD PACKED'],
                'use' => 'SPEED,TOURING,E-GRAVEL',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 510,
                'ean_code' => '3528706213281',
                'price_eur' => null,
                'image_url' => null,
            ],

            // ── ROAD ───────────────────────────────────────────────────────
            [
                'global_id' => 'BI-127',
                'web_range_name' => 'Power Cup TLR',
                'segment' => 'ROAD',
                'width_etrto' => 25,
                'diameter_etrto' => 622,
                'tpi' => 120,
                'min_pressure_bar' => 5.0,
                'max_pressure_bar' => 8.0,
                'rubber_tech' => 'GUM-X',
                'casing_tech' => 'TUBELESS SHIELD',
                'reinforcement_tech' => null,
                'ebike_tech' => null,
                'terrain_types' => ['ASPHALT'],
                'use' => 'RACING',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 260,
                'ean_code' => '3528701764214',
                'price_eur' => null,
                'image_url' => null,
            ],
            [
                'global_id' => 'BI-121',
                'web_range_name' => 'Power Road TLR',
                'segment' => 'ROAD',
                'width_etrto' => 25,
                'diameter_etrto' => 622,
                'tpi' => 120,
                'min_pressure_bar' => 5.0,
                'max_pressure_bar' => 8.0,
                'rubber_tech' => null,
                'casing_tech' => null,
                'reinforcement_tech' => null,
                'ebike_tech' => null,
                'terrain_types' => ['ASPHALT'],
                'use' => 'RACING',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 275,
                'ean_code' => '3528708761728',
                'price_eur' => null,
                'image_url' => null,
            ],
            [
                'global_id' => 'BI-151',
                'web_range_name' => 'Lithion 4',
                'segment' => 'ROAD',
                'width_etrto' => 23,
                'diameter_etrto' => 622,
                'tpi' => 55,
                'min_pressure_bar' => 6.0,
                'max_pressure_bar' => 8.0,
                'rubber_tech' => 'MAGI-X',
                'casing_tech' => null,
                'reinforcement_tech' => null,
                'ebike_tech' => 'E-BIKE READY',
                'terrain_types' => ['ASPHALT'],
                'use' => 'ENDURANCE,E-ROAD',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 240,
                'ean_code' => '3528703037217',
                'price_eur' => null,
                'image_url' => null,
            ],

            // ── MTB ────────────────────────────────────────────────────────
            [
                'global_id' => 'BI-132',
                'web_range_name' => 'Wild Enduro MS',
                'segment' => 'MTB',
                'width_etrto' => 61,
                'diameter_etrto' => 584,
                'tpi' => 55,
                'min_pressure_bar' => 1.5,
                'max_pressure_bar' => 4.0,
                'rubber_tech' => 'MAGI-X',
                'casing_tech' => 'BEAD TO BEAD SHIELD,PINCH PROTECTION',
                'reinforcement_tech' => null,
                'ebike_tech' => 'E-BIKE READY',
                'terrain_types' => ['OFFROAD MIXED', 'OFFROAD SOFT'],
                'use' => 'ENDURO,E-ENDURO',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 1235,
                'ean_code' => '3528707370259',
                'price_eur' => null,
                'image_url' => null,
            ],
            [
                'global_id' => 'BI-178',
                'web_range_name' => 'Force XC3',
                'segment' => 'MTB',
                'width_etrto' => 55,
                'diameter_etrto' => 622,
                'tpi' => 120,
                'min_pressure_bar' => null,
                'max_pressure_bar' => 2.5,
                'rubber_tech' => 'GUM-X',
                'casing_tech' => 'BEAD TO BEAD SHIELD',
                'reinforcement_tech' => null,
                'ebike_tech' => 'E-BIKE READY',
                'terrain_types' => ['OFFROAD MIXED'],
                'use' => 'CROSS COUNTRY,E-XC',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 700,
                'ean_code' => '3528707040510',
                'price_eur' => null,
                'image_url' => null,
            ],
            [
                'global_id' => 'BI-102',
                'web_range_name' => 'DH22',
                'segment' => 'MTB',
                'width_etrto' => 61,
                'diameter_etrto' => 584,
                'tpi' => 55,
                'min_pressure_bar' => 1.5,
                'max_pressure_bar' => 4.0,
                'rubber_tech' => 'MAGI-X',
                'casing_tech' => 'BEAD TO BEAD SHIELD,PINCH PROTECTION',
                'reinforcement_tech' => null,
                'ebike_tech' => null,
                'terrain_types' => ['OFFROAD MIXED', 'OFFROAD SOFT'],
                'use' => 'DOWNHILL,ENDURO,E-ENDURO',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 1440,
                'ean_code' => '3528706239885',
                'price_eur' => null,
                'image_url' => null,
            ],

            // ── EBIKE_URBAN ────────────────────────────────────────────────
            [
                'global_id' => 'BI-158',
                'web_range_name' => 'City Street',
                'segment' => 'EBIKE_URBAN',
                'width_etrto' => 40,
                'diameter_etrto' => 559,
                'tpi' => 62,
                'min_pressure_bar' => 2.5,
                'max_pressure_bar' => 6.0,
                'rubber_tech' => 'MAGI-X',
                'casing_tech' => 'CITY SHIELD',
                'reinforcement_tech' => 'BEAD TO BEAD PROTECTION, HD PROTECTION',
                'ebike_tech' => 'E-BIKE READY',
                'terrain_types' => ['ASPHALT'],
                'use' => 'URBAN,E-CITY',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 630,
                'ean_code' => '3528707932389',
                'price_eur' => null,
                'image_url' => null,
            ],
            [
                'global_id' => 'BI-166',
                'web_range_name' => 'City Touring',
                'segment' => 'EBIKE_URBAN',
                'width_etrto' => 35,
                'diameter_etrto' => 349,
                'tpi' => 62,
                'min_pressure_bar' => null,
                'max_pressure_bar' => 7.5,
                'rubber_tech' => 'MAGI-X',
                'casing_tech' => 'CITY SHIELD',
                'reinforcement_tech' => 'BEAD TO BEAD PROTECTION, HD PROTECTION',
                'ebike_tech' => 'E-BIKE READY',
                'terrain_types' => ['ASPHALT', 'OFFROAD HARD PACKED'],
                'use' => 'TOURING,E-CITY,E-TOURING',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 370,
                'ean_code' => '3528709213691',
                'price_eur' => null,
                'image_url' => null,
            ],
            [
                'global_id' => 'BI-50',
                'web_range_name' => 'Protek Max',
                'segment' => 'EBIKE_URBAN',
                'width_etrto' => 37,
                'diameter_etrto' => 406,
                'tpi' => 30,
                'min_pressure_bar' => 2.5,
                'max_pressure_bar' => 5.0,
                'rubber_tech' => null,
                'casing_tech' => 'MAX PROTECTION',
                'reinforcement_tech' => null,
                'ebike_tech' => 'E-BIKE READY',
                'terrain_types' => ['ASPHALT', 'OFFROAD HARD PACKED'],
                'use' => 'TOURING',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 625,
                'ean_code' => '3528704158652',
                'price_eur' => null,
                'image_url' => null,
            ],
            [
                'global_id' => 'BI-165',
                'web_range_name' => 'City Cargo',
                'segment' => 'EBIKE_URBAN',
                'width_etrto' => 55,
                'diameter_etrto' => 406,
                'tpi' => 62,
                'min_pressure_bar' => 1.8,
                'max_pressure_bar' => 5.0,
                'rubber_tech' => 'MAGI-X',
                'casing_tech' => 'CARGO SHIELD',
                'reinforcement_tech' => null,
                'ebike_tech' => 'E-50',
                'terrain_types' => ['ASPHALT'],
                'use' => 'CARGO,URBAN,E-CARGO,E-CITY',
                'expected_life_km' => null,
                'rolling_resistance_watts' => null,
                'weight_g' => 900,
                'ean_code' => '3528703495123',
                'price_eur' => null,
                'image_url' => null,
            ],
        ];
    }
}
